Repository Daniellescipio/shotlistapp, pull requests merged in 2021-02, with the labels that each got.

#1 Danny/readme update
  .gitignore
  README.md
Labels: documentation

#22 Update dependencies
  .eslintrc.json
  package.json
  packages/server/index.js
  yarn.lock
Labels: bug

#23 Refactor
  .gitignore
  .swp
  package.json
  packages/server/helpers/generateSeedData.js
  packages/server/index.js
  packages/server/package.json
  packages/server/routes/personRouter.js
  packages/server/routes/productionRouter.js
  packages/server/routes/sceneRouter.js
  packages/server/routes/shotRouter.js
  packages/server/seeds/people/people.js
  packages/web/package.json
  yarn.lock
Labels: refactor

#24 initialize ui-lib package with storybook installed
  packages/ui-lib/.storybook/main.js
  packages/ui-lib/.storybook/preview.js
  packages/ui-lib/package.json
  packages/ui-lib/src/Button.js
  packages/ui-lib/src/stories/Button.stories.js
  packages/ui-lib/src/styles/button.css
  yarn.lock
Labels: enhancement

#26 add grommet dependencies to ui-lib
  packages/ui-lib/package.json
Labels: enhancement

#33 Update dependencies
  package.json
  packages/server/package.json
  packages/ui-lib/package.json
  packages/utils/package.json
  packages/web/package.json
  yarn.lock
Labels: bug
